### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by grasmash**
Updating to match https://github.com/acquia/blt/blob/10.0.x/subtree-splits/blt-project/composer.json

### CODE REVIEW

**Comment by mikemadison13** [comment]
@grasmash i don't have the ability to restart your build, so i'm not able to test if it was a fluke or if there's a problem. could you check my access on this project please? happy to do some testing / debugging.

**Comment by TravisCarden** [comment]
I restarted the build, @mikemadison13, and it failed again.

**Comment by grasmash** [comment]
I'll try clearing the caches and restarting.

**Comment by TravisCarden** [comment]
What say you, @mikemadison13?

**Comment by grasmash** [comment]
This PR should be merged at the same time as https://github.com/acquia/blt/pull/3274

**Comment by mikemadison13** [comment]
I cannot merge this PR, I don't think i'm an admin on this project. @grasmash  can you promote me please?

**Pull request merged**
