### PR TITLE
Incorrect .gitignore file

### PR DESCRIPTION
**Pull request by netw3rker**
Removed incorrect .gitignore file that breaks normal BLT behavior. With this file here, the correct .gitignore file will not be copied over, and the source artifacts will be added to the repository as a result.

### CODE REVIEW

**Comment by danepowell** [comment]
@grasmash it looks like you added the referenced file in the 9.x branch, you should probably review this

**Comment by netw3rker** [comment]
i'm no good at stuff like this, but is it maybe worth adding a ci test that maybe adds a file to a known ignore location and does a `git status` to check if things are properly being ignored going forward?

**Comment by grasmash** [comment]
This file is only used internally. What is the issue that caused this PR to be opened?

**Comment by netw3rker** [comment]
when you do `composer create-project acquia/blt-project:9.x-dev projectname` the resulting gitignore in the root is this one instead of the expected one.

**Pull request merged**
